//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Nebra.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="NebraParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface INebraVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScript([NotNull] NebraParser.ScriptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] NebraParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EmptyStat</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptyStat([NotNull] NebraParser.EmptyStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AssignStat</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignStat([NotNull] NebraParser.AssignStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FunctionCallStat</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCallStat([NotNull] NebraParser.FunctionCallStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NewStat</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewStat([NotNull] NebraParser.NewStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IncDecStat_</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncDecStat_([NotNull] NebraParser.IncDecStat_Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LabelStat</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabelStat([NotNull] NebraParser.LabelStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BreakStat</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakStat([NotNull] NebraParser.BreakStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ContinueStat</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinueStat([NotNull] NebraParser.ContinueStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GotoStat</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGotoStat([NotNull] NebraParser.GotoStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeferStat_</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeferStat_([NotNull] NebraParser.DeferStat_Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GuardStat_</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGuardStat_([NotNull] NebraParser.GuardStat_Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DoStat</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoStat([NotNull] NebraParser.DoStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>WhileStat</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStat([NotNull] NebraParser.WhileStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RepeatStat</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRepeatStat([NotNull] NebraParser.RepeatStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IfStat_</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStat_([NotNull] NebraParser.IfStat_Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NumericForStat</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumericForStat([NotNull] NebraParser.NumericForStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GenericForStat</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericForStat([NotNull] NebraParser.GenericForStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FunctionDeclStat</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDeclStat([NotNull] NebraParser.FunctionDeclStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LocalFunctionDeclStat</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalFunctionDeclStat([NotNull] NebraParser.LocalFunctionDeclStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LocalDeclStat</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalDeclStat([NotNull] NebraParser.LocalDeclStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EnumDeclStat</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumDeclStat([NotNull] NebraParser.EnumDeclStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ImportStat_</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportStat_([NotNull] NebraParser.ImportStat_Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExportStat_</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExportStat_([NotNull] NebraParser.ExportStat_Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclareStat_</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareStat_([NotNull] NebraParser.DeclareStat_Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MatchStat_</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatchStat_([NotNull] NebraParser.MatchStat_Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ClassDeclStat</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassDeclStat([NotNull] NebraParser.ClassDeclStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>InterfaceDeclStat</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceDeclStat([NotNull] NebraParser.InterfaceDeclStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExtendDeclStat</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtendDeclStat([NotNull] NebraParser.ExtendDeclStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SuperCallStat</c>
	/// labeled alternative in <see cref="NebraParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSuperCallStat([NotNull] NebraParser.SuperCallStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.doBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoBlock([NotNull] NebraParser.DoBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.whileLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileLoop([NotNull] NebraParser.WhileLoopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.repeatLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRepeatLoop([NotNull] NebraParser.RepeatLoopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.ifStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStat([NotNull] NebraParser.IfStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.elseIfClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseIfClause([NotNull] NebraParser.ElseIfClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.elseClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseClause([NotNull] NebraParser.ElseClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.numericFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumericFor([NotNull] NebraParser.NumericForContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.genericFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericFor([NotNull] NebraParser.GenericForContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabel([NotNull] NebraParser.LabelContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PostIncStat</c>
	/// labeled alternative in <see cref="NebraParser.incDecStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostIncStat([NotNull] NebraParser.PostIncStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PostDecStat</c>
	/// labeled alternative in <see cref="NebraParser.incDecStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostDecStat([NotNull] NebraParser.PostDecStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PreIncStat</c>
	/// labeled alternative in <see cref="NebraParser.incDecStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPreIncStat([NotNull] NebraParser.PreIncStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PreDecStat</c>
	/// labeled alternative in <see cref="NebraParser.incDecStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPreDecStat([NotNull] NebraParser.PreDecStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeferCallStat</c>
	/// labeled alternative in <see cref="NebraParser.deferStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeferCallStat([NotNull] NebraParser.DeferCallStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeferBlockStat</c>
	/// labeled alternative in <see cref="NebraParser.deferStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeferBlockStat([NotNull] NebraParser.DeferBlockStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.guardStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGuardStat([NotNull] NebraParser.GuardStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.returnStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStat([NotNull] NebraParser.ReturnStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.functionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDecl([NotNull] NebraParser.FunctionDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.localFunctionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalFunctionDecl([NotNull] NebraParser.LocalFunctionDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.localDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalDecl([NotNull] NebraParser.LocalDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.annotationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationList([NotNull] NebraParser.AnnotationListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotation([NotNull] NebraParser.AnnotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.annotationArgList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationArgList([NotNull] NebraParser.AnnotationArgListContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NamedAnnotationArg</c>
	/// labeled alternative in <see cref="NebraParser.annotationArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamedAnnotationArg([NotNull] NebraParser.NamedAnnotationArgContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PositionalAnnotationArg</c>
	/// labeled alternative in <see cref="NebraParser.annotationArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPositionalAnnotationArg([NotNull] NebraParser.PositionalAnnotationArgContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ImportFrom</c>
	/// labeled alternative in <see cref="NebraParser.importStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportFrom([NotNull] NebraParser.ImportFromContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ImportSideEffect</c>
	/// labeled alternative in <see cref="NebraParser.importStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportSideEffect([NotNull] NebraParser.ImportSideEffectContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NamedImport</c>
	/// labeled alternative in <see cref="NebraParser.importBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamedImport([NotNull] NebraParser.NamedImportContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DefaultImport</c>
	/// labeled alternative in <see cref="NebraParser.importBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefaultImport([NotNull] NebraParser.DefaultImportContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NamespaceImport</c>
	/// labeled alternative in <see cref="NebraParser.importBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespaceImport([NotNull] NebraParser.NamespaceImportContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.importName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportName([NotNull] NebraParser.ImportNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.enumDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumDecl([NotNull] NebraParser.EnumDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.enumMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumMember([NotNull] NebraParser.EnumMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.classDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassDecl([NotNull] NebraParser.ClassDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ClassFieldMember</c>
	/// labeled alternative in <see cref="NebraParser.classMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassFieldMember([NotNull] NebraParser.ClassFieldMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ClassMethodMember</c>
	/// labeled alternative in <see cref="NebraParser.classMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassMethodMember([NotNull] NebraParser.ClassMethodMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ClassAbstractMethodMember</c>
	/// labeled alternative in <see cref="NebraParser.classMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassAbstractMethodMember([NotNull] NebraParser.ClassAbstractMethodMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ClassConstructorMember</c>
	/// labeled alternative in <see cref="NebraParser.classMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassConstructorMember([NotNull] NebraParser.ClassConstructorMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ClassOperatorMember</c>
	/// labeled alternative in <see cref="NebraParser.classMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassOperatorMember([NotNull] NebraParser.ClassOperatorMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ClassAccessorMember</c>
	/// labeled alternative in <see cref="NebraParser.classMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassAccessorMember([NotNull] NebraParser.ClassAccessorMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OpSymPlus</c>
	/// labeled alternative in <see cref="NebraParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpSymPlus([NotNull] NebraParser.OpSymPlusContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OpSymMinus</c>
	/// labeled alternative in <see cref="NebraParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpSymMinus([NotNull] NebraParser.OpSymMinusContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OpSymStar</c>
	/// labeled alternative in <see cref="NebraParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpSymStar([NotNull] NebraParser.OpSymStarContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OpSymSlash</c>
	/// labeled alternative in <see cref="NebraParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpSymSlash([NotNull] NebraParser.OpSymSlashContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OpSymDSlash</c>
	/// labeled alternative in <see cref="NebraParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpSymDSlash([NotNull] NebraParser.OpSymDSlashContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OpSymPercent</c>
	/// labeled alternative in <see cref="NebraParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpSymPercent([NotNull] NebraParser.OpSymPercentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OpSymCaret</c>
	/// labeled alternative in <see cref="NebraParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpSymCaret([NotNull] NebraParser.OpSymCaretContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OpSymConcat</c>
	/// labeled alternative in <see cref="NebraParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpSymConcat([NotNull] NebraParser.OpSymConcatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OpSymEq</c>
	/// labeled alternative in <see cref="NebraParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpSymEq([NotNull] NebraParser.OpSymEqContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OpSymLt</c>
	/// labeled alternative in <see cref="NebraParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpSymLt([NotNull] NebraParser.OpSymLtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OpSymLte</c>
	/// labeled alternative in <see cref="NebraParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpSymLte([NotNull] NebraParser.OpSymLteContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OpSymHash</c>
	/// labeled alternative in <see cref="NebraParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpSymHash([NotNull] NebraParser.OpSymHashContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.interfaceDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceDecl([NotNull] NebraParser.InterfaceDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.typeParamList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeParamList([NotNull] NebraParser.TypeParamListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.typeParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeParam([NotNull] NebraParser.TypeParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.classRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassRef([NotNull] NebraParser.ClassRefContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>InterfaceFieldMember</c>
	/// labeled alternative in <see cref="NebraParser.interfaceMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceFieldMember([NotNull] NebraParser.InterfaceFieldMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>InterfaceDefaultMethodMember</c>
	/// labeled alternative in <see cref="NebraParser.interfaceMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceDefaultMethodMember([NotNull] NebraParser.InterfaceDefaultMethodMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>InterfaceMethodMember</c>
	/// labeled alternative in <see cref="NebraParser.interfaceMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceMethodMember([NotNull] NebraParser.InterfaceMethodMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclareInterfaceFieldMember</c>
	/// labeled alternative in <see cref="NebraParser.declareInterfaceMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareInterfaceFieldMember([NotNull] NebraParser.DeclareInterfaceFieldMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclareInterfaceMethodMember</c>
	/// labeled alternative in <see cref="NebraParser.declareInterfaceMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareInterfaceMethodMember([NotNull] NebraParser.DeclareInterfaceMethodMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.extendDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtendDecl([NotNull] NebraParser.ExtendDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.extendMethod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtendMethod([NotNull] NebraParser.ExtendMethodContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExportFunction</c>
	/// labeled alternative in <see cref="NebraParser.exportStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExportFunction([NotNull] NebraParser.ExportFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExportLocalFunction</c>
	/// labeled alternative in <see cref="NebraParser.exportStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExportLocalFunction([NotNull] NebraParser.ExportLocalFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExportLocal</c>
	/// labeled alternative in <see cref="NebraParser.exportStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExportLocal([NotNull] NebraParser.ExportLocalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExportEnum</c>
	/// labeled alternative in <see cref="NebraParser.exportStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExportEnum([NotNull] NebraParser.ExportEnumContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExportClass</c>
	/// labeled alternative in <see cref="NebraParser.exportStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExportClass([NotNull] NebraParser.ExportClassContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExportInterface</c>
	/// labeled alternative in <see cref="NebraParser.exportStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExportInterface([NotNull] NebraParser.ExportInterfaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.matchStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatchStat([NotNull] NebraParser.MatchStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.matchExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatchExpr([NotNull] NebraParser.MatchExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.matchArm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatchArm([NotNull] NebraParser.MatchArmContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.matchExprArm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatchExprArm([NotNull] NebraParser.MatchExprArmContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BindingPattern</c>
	/// labeled alternative in <see cref="NebraParser.matchPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBindingPattern([NotNull] NebraParser.BindingPatternContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ValuePattern</c>
	/// labeled alternative in <see cref="NebraParser.matchPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValuePattern([NotNull] NebraParser.ValuePatternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.declareStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareStat([NotNull] NebraParser.DeclareStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclareFunction</c>
	/// labeled alternative in <see cref="NebraParser.declareBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareFunction([NotNull] NebraParser.DeclareFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclareVariable</c>
	/// labeled alternative in <see cref="NebraParser.declareBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareVariable([NotNull] NebraParser.DeclareVariableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclareModule</c>
	/// labeled alternative in <see cref="NebraParser.declareBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareModule([NotNull] NebraParser.DeclareModuleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclareEnum</c>
	/// labeled alternative in <see cref="NebraParser.declareBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareEnum([NotNull] NebraParser.DeclareEnumContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclareClass</c>
	/// labeled alternative in <see cref="NebraParser.declareBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareClass([NotNull] NebraParser.DeclareClassContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclareInterface</c>
	/// labeled alternative in <see cref="NebraParser.declareBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareInterface([NotNull] NebraParser.DeclareInterfaceContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclareClassFieldMember</c>
	/// labeled alternative in <see cref="NebraParser.declareClassMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareClassFieldMember([NotNull] NebraParser.DeclareClassFieldMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclareClassMethodMember</c>
	/// labeled alternative in <see cref="NebraParser.declareClassMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareClassMethodMember([NotNull] NebraParser.DeclareClassMethodMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclareClassConstructorMember</c>
	/// labeled alternative in <see cref="NebraParser.declareClassMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareClassConstructorMember([NotNull] NebraParser.DeclareClassConstructorMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclareClassOperatorMember</c>
	/// labeled alternative in <see cref="NebraParser.declareClassMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareClassOperatorMember([NotNull] NebraParser.DeclareClassOperatorMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclareClassAccessorMember</c>
	/// labeled alternative in <see cref="NebraParser.declareClassMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareClassAccessorMember([NotNull] NebraParser.DeclareClassAccessorMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.funcSignature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncSignature([NotNull] NebraParser.FuncSignatureContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PredicateReturn</c>
	/// labeled alternative in <see cref="NebraParser.funcReturn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredicateReturn([NotNull] NebraParser.PredicateReturnContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PlainReturn</c>
	/// labeled alternative in <see cref="NebraParser.funcReturn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlainReturn([NotNull] NebraParser.PlainReturnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.declareModuleBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareModuleBlock([NotNull] NebraParser.DeclareModuleBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.declareEnumMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareEnumMember([NotNull] NebraParser.DeclareEnumMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ModuleDeclareFunction</c>
	/// labeled alternative in <see cref="NebraParser.declareModuleMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleDeclareFunction([NotNull] NebraParser.ModuleDeclareFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ModuleDeclareVariable</c>
	/// labeled alternative in <see cref="NebraParser.declareModuleMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleDeclareVariable([NotNull] NebraParser.ModuleDeclareVariableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ModuleDeclareEnum</c>
	/// labeled alternative in <see cref="NebraParser.declareModuleMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleDeclareEnum([NotNull] NebraParser.ModuleDeclareEnumContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ModuleDeclareClass</c>
	/// labeled alternative in <see cref="NebraParser.declareModuleMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleDeclareClass([NotNull] NebraParser.ModuleDeclareClassContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ModuleDeclareInterface</c>
	/// labeled alternative in <see cref="NebraParser.declareModuleMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleDeclareInterface([NotNull] NebraParser.ModuleDeclareInterfaceContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ModuleDeclareExtend</c>
	/// labeled alternative in <see cref="NebraParser.declareModuleMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleDeclareExtend([NotNull] NebraParser.ModuleDeclareExtendContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.declareExtendMethod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareExtendMethod([NotNull] NebraParser.DeclareExtendMethodContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.funcName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncName([NotNull] NebraParser.FuncNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.funcBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncBody([NotNull] NebraParser.FuncBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParamListWithNames</c>
	/// labeled alternative in <see cref="NebraParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamListWithNames([NotNull] NebraParser.ParamListWithNamesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParamListVararg</c>
	/// labeled alternative in <see cref="NebraParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamListVararg([NotNull] NebraParser.ParamListVarargContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam([NotNull] NebraParser.ParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.varargParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarargParam([NotNull] NebraParser.VarargParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.varList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarList([NotNull] NebraParser.VarListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.nameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNameList([NotNull] NebraParser.NameListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.attribNameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribNameList([NotNull] NebraParser.AttribNameListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.attribName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribName([NotNull] NebraParser.AttribNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.attrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttrib([NotNull] NebraParser.AttribContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.exprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprList([NotNull] NebraParser.ExprListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.typeAnnotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeAnnotation([NotNull] NebraParser.TypeAnnotationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UnionType</c>
	/// labeled alternative in <see cref="NebraParser.typeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnionType([NotNull] NebraParser.UnionTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PostfixType</c>
	/// labeled alternative in <see cref="NebraParser.typeSingle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfixType([NotNull] NebraParser.PostfixTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ArraySuffix</c>
	/// labeled alternative in <see cref="NebraParser.typeSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArraySuffix([NotNull] NebraParser.ArraySuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NullableSuffix</c>
	/// labeled alternative in <see cref="NebraParser.typeSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullableSuffix([NotNull] NebraParser.NullableSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NilType</c>
	/// labeled alternative in <see cref="NebraParser.typeAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNilType([NotNull] NebraParser.NilTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BareFunctionType</c>
	/// labeled alternative in <see cref="NebraParser.typeAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBareFunctionType([NotNull] NebraParser.BareFunctionTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NamedType</c>
	/// labeled alternative in <see cref="NebraParser.typeAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamedType([NotNull] NebraParser.NamedTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncType</c>
	/// labeled alternative in <see cref="NebraParser.typeAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncType([NotNull] NebraParser.FuncTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TableType_</c>
	/// labeled alternative in <see cref="NebraParser.typeAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableType_([NotNull] NebraParser.TableType_Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GroupedOrTupleType</c>
	/// labeled alternative in <see cref="NebraParser.typeAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroupedOrTupleType([NotNull] NebraParser.GroupedOrTupleTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VariadicType</c>
	/// labeled alternative in <see cref="NebraParser.typeAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariadicType([NotNull] NebraParser.VariadicTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.typeArgList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeArgList([NotNull] NebraParser.TypeArgListContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ConcreteTypeArg</c>
	/// labeled alternative in <see cref="NebraParser.typeArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConcreteTypeArg([NotNull] NebraParser.ConcreteTypeArgContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>WildcardTypeArg</c>
	/// labeled alternative in <see cref="NebraParser.typeArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWildcardTypeArg([NotNull] NebraParser.WildcardTypeArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.functionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionType([NotNull] NebraParser.FunctionTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.typeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeList([NotNull] NebraParser.TypeListContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EmptyTableType</c>
	/// labeled alternative in <see cref="NebraParser.tableType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptyTableType([NotNull] NebraParser.EmptyTableTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MapType</c>
	/// labeled alternative in <see cref="NebraParser.tableType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapType([NotNull] NebraParser.MapTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>StructType</c>
	/// labeled alternative in <see cref="NebraParser.tableType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructType([NotNull] NebraParser.StructTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.structField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructField([NotNull] NebraParser.StructFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PreIncExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPreIncExpr([NotNull] NebraParser.PreIncExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BitwiseOrExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwiseOrExpr([NotNull] NebraParser.BitwiseOrExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ComparisonExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparisonExpr([NotNull] NebraParser.ComparisonExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TypeCheckExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeCheckExpr([NotNull] NebraParser.TypeCheckExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FunctionDefExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDefExpr([NotNull] NebraParser.FunctionDefExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PreDecExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPreDecExpr([NotNull] NebraParser.PreDecExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LogicalAndExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalAndExpr([NotNull] NebraParser.LogicalAndExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NonNilAssertExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNonNilAssertExpr([NotNull] NebraParser.NonNilAssertExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FalseLiteral</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFalseLiteral([NotNull] NebraParser.FalseLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MultiplicativeExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeExpr([NotNull] NebraParser.MultiplicativeExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AltLogicalOrExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAltLogicalOrExpr([NotNull] NebraParser.AltLogicalOrExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TrueLiteral</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrueLiteral([NotNull] NebraParser.TrueLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PostIncExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostIncExpr([NotNull] NebraParser.PostIncExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SuperCallExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSuperCallExpr([NotNull] NebraParser.SuperCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NilCoalesceExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNilCoalesceExpr([NotNull] NebraParser.NilCoalesceExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PostDecExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostDecExpr([NotNull] NebraParser.PostDecExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BitShiftExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitShiftExpr([NotNull] NebraParser.BitShiftExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BitwiseAndExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwiseAndExpr([NotNull] NebraParser.BitwiseAndExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AltLogicalNotExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAltLogicalNotExpr([NotNull] NebraParser.AltLogicalNotExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AltLogicalAndExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAltLogicalAndExpr([NotNull] NebraParser.AltLogicalAndExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UnaryExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpr([NotNull] NebraParser.UnaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>InstanceOfExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstanceOfExpr([NotNull] NebraParser.InstanceOfExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PrefixExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrefixExpr([NotNull] NebraParser.PrefixExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TypeOfExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeOfExpr([NotNull] NebraParser.TypeOfExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PowerExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPowerExpr([NotNull] NebraParser.PowerExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ConcatExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConcatExpr([NotNull] NebraParser.ConcatExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LogicalOrExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalOrExpr([NotNull] NebraParser.LogicalOrExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AwaitExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAwaitExpr([NotNull] NebraParser.AwaitExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>StringLiteral</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringLiteral([NotNull] NebraParser.StringLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AdditiveExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveExpr([NotNull] NebraParser.AdditiveExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VarargExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarargExpr([NotNull] NebraParser.VarargExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NilLiteral</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNilLiteral([NotNull] NebraParser.NilLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NewExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewExpr([NotNull] NebraParser.NewExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BitwiseXorExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwiseXorExpr([NotNull] NebraParser.BitwiseXorExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NumberLiteral</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberLiteral([NotNull] NebraParser.NumberLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TypeCastExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeCastExpr([NotNull] NebraParser.TypeCastExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TableConstructorExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableConstructorExpr([NotNull] NebraParser.TableConstructorExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MatchExprExpr</c>
	/// labeled alternative in <see cref="NebraParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatchExprExpr([NotNull] NebraParser.MatchExprExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LtOp</c>
	/// labeled alternative in <see cref="NebraParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLtOp([NotNull] NebraParser.LtOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GtOp</c>
	/// labeled alternative in <see cref="NebraParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGtOp([NotNull] NebraParser.GtOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LteOp</c>
	/// labeled alternative in <see cref="NebraParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLteOp([NotNull] NebraParser.LteOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GteOp</c>
	/// labeled alternative in <see cref="NebraParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGteOp([NotNull] NebraParser.GteOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NeqOp</c>
	/// labeled alternative in <see cref="NebraParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNeqOp([NotNull] NebraParser.NeqOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AltNeqOp</c>
	/// labeled alternative in <see cref="NebraParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAltNeqOp([NotNull] NebraParser.AltNeqOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EqOp</c>
	/// labeled alternative in <see cref="NebraParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqOp([NotNull] NebraParser.EqOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LshiftOp</c>
	/// labeled alternative in <see cref="NebraParser.shiftOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLshiftOp([NotNull] NebraParser.LshiftOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RshiftOp</c>
	/// labeled alternative in <see cref="NebraParser.shiftOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRshiftOp([NotNull] NebraParser.RshiftOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AddOp</c>
	/// labeled alternative in <see cref="NebraParser.additiveOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddOp([NotNull] NebraParser.AddOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SubOp</c>
	/// labeled alternative in <see cref="NebraParser.additiveOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubOp([NotNull] NebraParser.SubOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MulOp</c>
	/// labeled alternative in <see cref="NebraParser.multiplicativeOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulOp([NotNull] NebraParser.MulOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DivOp</c>
	/// labeled alternative in <see cref="NebraParser.multiplicativeOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDivOp([NotNull] NebraParser.DivOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FloorDivOp</c>
	/// labeled alternative in <see cref="NebraParser.multiplicativeOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloorDivOp([NotNull] NebraParser.FloorDivOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ModOp</c>
	/// labeled alternative in <see cref="NebraParser.multiplicativeOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModOp([NotNull] NebraParser.ModOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LogicalNotOp</c>
	/// labeled alternative in <see cref="NebraParser.unaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalNotOp([NotNull] NebraParser.LogicalNotOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LengthOp</c>
	/// labeled alternative in <see cref="NebraParser.unaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLengthOp([NotNull] NebraParser.LengthOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NegateOp</c>
	/// labeled alternative in <see cref="NebraParser.unaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegateOp([NotNull] NebraParser.NegateOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BitwiseNotOp</c>
	/// labeled alternative in <see cref="NebraParser.unaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwiseNotOp([NotNull] NebraParser.BitwiseNotOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.prefixExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrefixExp([NotNull] NebraParser.PrefixExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NameVarOrExp</c>
	/// labeled alternative in <see cref="NebraParser.varOrExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNameVarOrExp([NotNull] NebraParser.NameVarOrExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParenVarOrExp</c>
	/// labeled alternative in <see cref="NebraParser.varOrExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenVarOrExp([NotNull] NebraParser.ParenVarOrExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DotSuffix</c>
	/// labeled alternative in <see cref="NebraParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDotSuffix([NotNull] NebraParser.DotSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OptDotSuffix</c>
	/// labeled alternative in <see cref="NebraParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptDotSuffix([NotNull] NebraParser.OptDotSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IndexSuffix</c>
	/// labeled alternative in <see cref="NebraParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexSuffix([NotNull] NebraParser.IndexSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MethodCallSuffix</c>
	/// labeled alternative in <see cref="NebraParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodCallSuffix([NotNull] NebraParser.MethodCallSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CallSuffix</c>
	/// labeled alternative in <see cref="NebraParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallSuffix([NotNull] NebraParser.CallSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OptCallSuffix</c>
	/// labeled alternative in <see cref="NebraParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptCallSuffix([NotNull] NebraParser.OptCallSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NameVar</c>
	/// labeled alternative in <see cref="NebraParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNameVar([NotNull] NebraParser.NameVarContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FieldVar</c>
	/// labeled alternative in <see cref="NebraParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldVar([NotNull] NebraParser.FieldVarContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IndexVar</c>
	/// labeled alternative in <see cref="NebraParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexVar([NotNull] NebraParser.IndexVarContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DirectCall</c>
	/// labeled alternative in <see cref="NebraParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDirectCall([NotNull] NebraParser.DirectCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MethodCall</c>
	/// labeled alternative in <see cref="NebraParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodCall([NotNull] NebraParser.MethodCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParenArgs</c>
	/// labeled alternative in <see cref="NebraParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenArgs([NotNull] NebraParser.ParenArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TableArgs</c>
	/// labeled alternative in <see cref="NebraParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableArgs([NotNull] NebraParser.TableArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>StringArgs</c>
	/// labeled alternative in <see cref="NebraParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringArgs([NotNull] NebraParser.StringArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.functionDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDef([NotNull] NebraParser.FunctionDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.tableConstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableConstructor([NotNull] NebraParser.TableConstructorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.fieldList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldList([NotNull] NebraParser.FieldListContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BracketField</c>
	/// labeled alternative in <see cref="NebraParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBracketField([NotNull] NebraParser.BracketFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NameField</c>
	/// labeled alternative in <see cref="NebraParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNameField([NotNull] NebraParser.NameFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FunctionField</c>
	/// labeled alternative in <see cref="NebraParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionField([NotNull] NebraParser.FunctionFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ValueField</c>
	/// labeled alternative in <see cref="NebraParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueField([NotNull] NebraParser.ValueFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NebraParser.fieldSep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldSep([NotNull] NebraParser.FieldSepContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IntLit</c>
	/// labeled alternative in <see cref="NebraParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntLit([NotNull] NebraParser.IntLitContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>HexLit</c>
	/// labeled alternative in <see cref="NebraParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHexLit([NotNull] NebraParser.HexLitContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FloatLit</c>
	/// labeled alternative in <see cref="NebraParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloatLit([NotNull] NebraParser.FloatLitContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>HexFloatLit</c>
	/// labeled alternative in <see cref="NebraParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHexFloatLit([NotNull] NebraParser.HexFloatLitContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DoubleQuotedStr</c>
	/// labeled alternative in <see cref="NebraParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoubleQuotedStr([NotNull] NebraParser.DoubleQuotedStrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SingleQuotedStr</c>
	/// labeled alternative in <see cref="NebraParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleQuotedStr([NotNull] NebraParser.SingleQuotedStrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LongStr</c>
	/// labeled alternative in <see cref="NebraParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLongStr([NotNull] NebraParser.LongStrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>InterpolatedStr</c>
	/// labeled alternative in <see cref="NebraParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterpolatedStr([NotNull] NebraParser.InterpolatedStrContext context);
}
